# Generated by Django 3.2.7 on 2021-09-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchengine',
            name='search_date',
            field=models.DateField(),
        ),
    ]
